title: Finkel-Blog
description: "A Blog about things I learn and make"
author:
  name: "Rafael Finkelstein"
  email: "finkel.rf@gmail.com"
  url: "https://finkelrf.github.com"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Rafael Finkelstein"
year : "2020"
